#include "GrimeApp.h"
#include "Moose.h"
#include "AppFactory.h"

template<>
InputParameters validParams<GrimeApp>()
{
  InputParameters params = validParams<MooseApp>();
  return params;
}

GrimeApp::GrimeApp(const std::string & name, InputParameters & parameters) :
    MooseApp(name, parameters)
{
  srand(libMesh::processor_id());
  
  Moose::registerObjects(_factory);
  GrimeApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);
  GrimeApp::associateSyntax(_syntax, _action_factory);
}

GrimeApp::~GrimeApp()
{
}

void
GrimeApp::registerApps()
{
  registerApp(GrimeApp);
}

void
GrimeApp::registerObjects(Factory & factory)
{
}

void
GrimeApp::associateSyntax(Syntax & syntax, ActionFactory & action_factory)
{
}
